// import * as images from './image.js';

// export default {
//     images,
//     fonts:{
//         menuTitle: '16px',

//         footerTitle: '28px',
//         FooterContact: '18px',
//         FooterCompanyTime: '16px',
//         FooterHelp: '16px',
//         FooterSplitLine: '14px',
//         FooterCopyRight: '14px',

//         AccountUserName: '22px',
//         AccountPropertyTotal: '14px',
//         AccountPropertyTotalTitle: '18px',
//         AccountPropertyTotalNum: '22px',
//         AccountPropertyList: '14px',
//         AccountPropertyListTitle: '24px',
//         AccountSurplus: '14px',
//         AccountPropertyItemDetailText: '12px',
//         AccountHoldingTokenTitle: '22px',
//         AccountHoldingTokenTitleText: '14px',
//         AccountHoldingTokenDetail: '14px',
//         AccountHoldingTokenNum: '14px',
//         AccountOwnerTitle: '12px',
//         AccountOwnerText: '14px',
//     },
//     colors:{
//         menuLogoActiveBackground: '#132045',
//         menuBoxBackground: '#19284D',
//         menuTitleColor: '#8794BA',
//         menuTitleHoverColor: '#fff',
//         menuNumListHoverColor: '#4588FF',
//         menuSearchInputBackground: '#0A1533',
//         menuSearchInputColor: '#fff',
//         menuSearchInputPlaceholderColor: '#AABCEB',
//         menuSearchInputIconColor: '#c5c5c5',
//         menuSearchInputIconHoverColor: '#fff',
//         menuLanguageSelectDefaultColor: '#BDC9EC',
//         menuSubMainColor: '#fff',
//         menuSubMainBackground: '#22325E',
//         menuSubMainNewsBackground:'#4588FF',


//         footerBackground: '#21305D',
//         footerTitleColor: '#fff',
//         FooterContactColor:  '#fff',
//         FooterCompanyTimeColor: '#7C87A4',
//         FooterHelpColor: '#C5CFF6',
//         FooterSplitLineColor: '#C5CFF6',
//         FooterCopyRightColor: '#C5CFF6',
//         FooterCompanyTimeLineColor: '#2A3863',

//         AccountUserCardBackground: '#fff',
//         AccountUserNameColor: '#22325E',
//         AccountCreateNameColor: '#4588FF',
//         AccountUserAvatarColor: '#4588FF',
//         AccountPropertyTotalColor: '#19284D',
//         AccountPropertyTotalBackground: '#fff',
//         AccountPropertyTotalDivColor: '#fff',
//         AccountPropertyTotalDivBackground: '#19284D',
//         AccountPropertyListColor: '#19284D',
//         AccountPropertyListBackground: '#fff',
//         AccountPropertyListTitleColor: '#19284D',
//         AccountSurplusColor: '#19284D',
//         AccountPropertyItemHoverBackground: '#F9FBFE',
//         AccountHoldingTokenBackground: '#fff',
//         AccountHoldingTokenTitleColor: '#22325E',
//         AccountHoldingTokenTitleSplitColor: '#E7EBEF',
//         AccountHoldingTokenTitleTextColor: '#8B8B8B',
//         AccountHoldingTokenDetailColor: '#8C94A9',
//         AccountHoldingTokenNumColor: '#4588FF',
//         AccountOwnerBackground: '#F9FBFE ',
//         AccountOwnerTitleColor: '#22325E',
//         AccountOwnerTextColor: '#4588FF',
//     },
// }

export default {
  // images,
  fonts: {
    regularFont: 'PingFangSC-Regular, sans-serif',
    lightFont: 'PingFangSC-Light, sans-serif',
    semiboldFont: 'PingFangSC-Semibold, sans-serif',
    mediumFont: 'PingFangSC-Medium, sans-serif',
    font12: '12px',
    font14: '14px',
    font16: '16px',
    font18: '18px',
    font20: '20px',
    font22: '22px',
    font24: '24px',
    font26: '26px',
    font28: '28px',
    font36: '36px'
  },
  colors: {

    layoutBackground: '#22325E',
    headerBackground: '#22325E',
    mainBackground: '#e5e9f2',
    headerMenuTextUnFocus: '#8794BA',
    headerMenuDarkBackground: '#132045',
    footerMainBackground: '#22325E',
    cardBackground: '#fff',
    linkButtonBackground: '#3D68EB',
    tableHoverBackground: '#F6F9FD',
    antdSelectedItemBackground: '#EBF3FF',
    btnPointBackground: '#13B092',
    EmbellishmentBackground: '#00BD9A',
    linkTextColor: '#3D68EB',
    backgroundTextColor: '#fff',
    helpTextColor: '#BDC9EC',
    normalTextColor: '#22325E',
    smallTitleColor: '#8c94a9',
    tableSubTitle: '#515A6E',
    darkTextColor: '#19284D',

    cardHoverColor: '#f6f9fd',
    grayTextColor: '#E7EBEF',
    grayerTextColor: '#8E96AA',

    splitLinecolor: '#E7EBEF',

    antProgressInnerBackground: '#CADDFF',
    antProgressBgBackground: '#3D68EB'
  }
}
